[package]
categories = ["games", "simulation"]
description = "A small simulation game"
edition = "2021"
keywords = ["awt"]
license = "MIT"
name = "awt"
readme = "READEME.md"
repository = "https://github.com/b-n/awt"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.8.5", features = ['small_rng'] }
