[package]
name = "min-queue"
version = "0.1.0"
description = "Small abstraction around BinaryHeap to make a Min Queue instead of Max"
keywords = ["min", "binary-heap"]
readme = "README.md"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
