---
name: CI
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      RUSTFLAGS: -D warnings
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: artichoke/setup-rust/build-and-test@v1
        with:
          toolchain: "1.72.0"

      - name: Compile
        run: cargo build --verbose

      - name: Compile tests
        run: cargo test --workspace --no-run

      - name: Test
        run: cargo test --workspace

  check-awt:
    name: Check awt workspace
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: artichoke/setup-rust/lint-and-format@v1
        with:
          toolchain: "1.72.0"

      - name: Check artichoke formatting
        run: cargo +nightly fmt --check

      - name: Lint artichoke with Clippy
        run: cargo clippy --workspace --all-features --all-targets

      - name: Check artichoke with locked Cargo.lock
        run: cargo check --locked --workspace --all-targets --profile=test
